version: "3"
services:
  redis:
    container_name: circuit_redis
    image: redis
    ports:
      - "${DOCKER_COMPOSE_REDIS_PORT}:6379"
    networks:
      - codeamp
  postgres:
    container_name: circuit_postgres
    image: postgres
    ports:
      - "${DOCKER_COMPOSE_POSTGRES_PORT}:5432"
    volumes:
      - ./bootstrap/postgres:/docker-entrypoint-initdb.d
    networks:
      - codeamp
  circuit:
    image: codeamp:v001
    command: sh -c "reflex -c reflex.conf"
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        pull: 1
    ports:
      - "${DOCKER_COMPOSE_CIRCUIT_PORT}:3011"
    volumes:
      - .:/go/src/github.com/codeamp/circuit
      - /var/run/docker.sock:/var/run/docker.sock
      - ./credentials:/etc/secrets
    depends_on:
      - postgres
      - redis
    networks:
      - codeamp
networks:
  codeamp:
    driver: bridge
