---
environment: "development"
redis:
  username:
  password:
  server: "0.0.0.0:6379"
  database: "0"
  pool: "30"
  process: "1"
plugins:
  codeamp:
    workers: 1
    postgres:
      host: "0.0.0.0"
      port: "5432"
      user: "postgres"
      dbname: "codeamp"
      sslmode: "disable"
      password: ""
    service_address: ":3001"
